-- ============================================================
-- MMG EPM - Schema Patch v2
-- Run this if you already have the database from FRESH_INSTALL.sql
-- Adds new tables for Task Delays, Task Comments
-- ============================================================

USE MMG_EPM;
GO

-- Add TaskDelays if not exists
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='TaskDelays' AND SCHEMA_NAME(schema_id)='Project')
BEGIN
    CREATE TABLE Project.TaskDelays (
        Id          UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
        TaskId      UNIQUEIDENTIFIER NOT NULL REFERENCES Project.Tasks(Id),
        DelayType   NVARCHAR(50)     NOT NULL,
        DelayHours  DECIMAL(10,2)    NOT NULL,
        Description NVARCHAR(2000)   NULL,
        LoggedById  UNIQUEIDENTIFIER NOT NULL REFERENCES Auth.Users(Id),
        CreatedAt   DATETIME2        NOT NULL DEFAULT SYSUTCDATETIME(),
        UpdatedAt   DATETIME2        NOT NULL DEFAULT SYSUTCDATETIME(),
        CreatedById UNIQUEIDENTIFIER NULL,
        UpdatedById UNIQUEIDENTIFIER NULL,
        IsDeleted   BIT              NOT NULL DEFAULT 0,
        DeletedAt   DATETIME2        NULL
    );
    PRINT 'Created Project.TaskDelays';
END
GO

-- Add TaskComments if not exists
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='TaskComments' AND SCHEMA_NAME(schema_id)='Project')
BEGIN
    CREATE TABLE Project.TaskComments (
        Id              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
        TaskId          UNIQUEIDENTIFIER NOT NULL REFERENCES Project.Tasks(Id),
        UserId          UNIQUEIDENTIFIER NOT NULL REFERENCES Auth.Users(Id),
        Content         NVARCHAR(2000)   NOT NULL,
        ParentCommentId UNIQUEIDENTIFIER NULL,
        CreatedAt       DATETIME2        NOT NULL DEFAULT SYSUTCDATETIME(),
        UpdatedAt       DATETIME2        NOT NULL DEFAULT SYSUTCDATETIME(),
        CreatedById     UNIQUEIDENTIFIER NULL,
        UpdatedById     UNIQUEIDENTIFIER NULL,
        IsDeleted       BIT              NOT NULL DEFAULT 0,
        DeletedAt       DATETIME2        NULL,
        CONSTRAINT FK_TaskComments_Parent FOREIGN KEY (ParentCommentId) REFERENCES Project.TaskComments(Id)
    );
    PRINT 'Created Project.TaskComments';
END
GO

PRINT '=== Patch v2 complete ===';
GO

-- Add TaskDependencies
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name='TaskDependencies' AND SCHEMA_NAME(schema_id)='Project')
BEGIN
    CREATE TABLE Project.TaskDependencies (
        Id              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
        TaskId          UNIQUEIDENTIFIER NOT NULL REFERENCES Project.Tasks(Id),
        PredecessorId   UNIQUEIDENTIFIER NOT NULL REFERENCES Project.Tasks(Id),
        DependencyType  NVARCHAR(20)     NOT NULL DEFAULT 'FS',
        LagDays         INT              NOT NULL DEFAULT 0,
        CreatedAt       DATETIME2        NOT NULL DEFAULT SYSUTCDATETIME(),
        UpdatedAt       DATETIME2        NOT NULL DEFAULT SYSUTCDATETIME(),
        CreatedById     UNIQUEIDENTIFIER NULL,
        UpdatedById     UNIQUEIDENTIFIER NULL,
        IsDeleted       BIT              NOT NULL DEFAULT 0,
        DeletedAt       DATETIME2        NULL,
        CONSTRAINT UQ_TaskDependency UNIQUE (TaskId, PredecessorId)
    );
    PRINT 'Created Project.TaskDependencies';
END
GO

-- Add new columns to DPRReports for extended DPR fields
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('Project.DPRReports') AND name='LocationOfWork')
BEGIN
    ALTER TABLE Project.DPRReports ADD LocationOfWork  NVARCHAR(500) NULL;
    ALTER TABLE Project.DPRReports ADD WeatherType     NVARCHAR(50)  NULL;
    ALTER TABLE Project.DPRReports ADD PdfPath         NVARCHAR(1000) NULL;
    ALTER TABLE Project.DPRReports ADD IsAutoGenerated BIT           NOT NULL DEFAULT 0;
    PRINT 'DPRReports extended columns added';
END
GO

-- Add approval + trade columns to CrewAttendance
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('Project.CrewAttendance') AND name='ApprovalStatus')
BEGIN
    ALTER TABLE Project.CrewAttendance ADD ApprovalStatus    NVARCHAR(50)  NOT NULL DEFAULT 'Pending';
    ALTER TABLE Project.CrewAttendance ADD ApprovedById      UNIQUEIDENTIFIER NULL;
    ALTER TABLE Project.CrewAttendance ADD ApprovedAt        DATETIME2 NULL;
    ALTER TABLE Project.CrewAttendance ADD RejectionRemarks  NVARCHAR(500) NULL;
    ALTER TABLE Project.CrewAttendance ADD TradeCode         NVARCHAR(100) NULL;
    ALTER TABLE Project.CrewAttendance ADD PlannedCount      INT NULL;
    ALTER TABLE Project.CrewAttendance ADD ActualCount       INT NULL;
    PRINT 'CrewAttendance approval columns added';
END
GO

-- Add FK for ApprovedBy on CrewAttendance
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name='FK_CrewAttendance_ApprovedBy')
    ALTER TABLE Project.CrewAttendance
        ADD CONSTRAINT FK_CrewAttendance_ApprovedBy
        FOREIGN KEY (ApprovedById) REFERENCES Auth.Users(Id);
GO

PRINT '=== Patch v3 complete ===';
GO
