using Microsoft.EntityFrameworkCore;
using MMG.EPM.API.Data;
using MMG.EPM.API.Domain.DTOs;
using MMG.EPM.API.Domain.Entities;

namespace MMG.EPM.API.Infrastructure.Services;

// ─── DPR Service Interface ─────────────────────────────────────

public interface IDprService
{
    Task<DprCompiledData> CompileDprSectionsAsync(Guid projectId, DateTime date);
    string GenerateDprHtml(DPRReport dpr, DprCompiledData data);
    Task AutoGenerateDailyDprsAsync();
}

public record DprCompiledData(
    List<DprTaskSection>  WorkProgress,
    List<DprDelaySection> Delays,
    List<DprLabourSection> Labour,
    List<DprRiskSection>  Risks,
    int TotalLabour, int TotalEquipment);

// ─── DPR Service Implementation ────────────────────────────────

public class DprService : IDprService
{
    private readonly AppDbContext _db;
    private readonly ILogger<DprService> _logger;

    public DprService(AppDbContext db, ILogger<DprService> logger)
    { _db = db; _logger = logger; }

    public async Task<DprCompiledData> CompileDprSectionsAsync(Guid projectId, DateTime date)
    {
        var targetDate = date.Date;

        // 1. Work Progress — tasks updated today
        var workProgress = await _db.WorkProgress
            .Include(wp => wp.Task)
            .Include(wp => wp.UpdatedBy)
            .Where(wp => wp.TaskId != null
                && wp.Task.ProjectId == projectId
                && wp.ReportedAt.Date == targetDate
                && !wp.IsDeleted)
            .Select(wp => new DprTaskSection(
                wp.Task.Name,
                wp.ProgressPercentage,
                wp.Task.Status,
                wp.Notes))
            .ToListAsync();

        // 2. Delays — logged today
        var delays = await _db.TaskDelays
            .Include(d => d.Task)
            .Where(d => d.Task.ProjectId == projectId
                && d.CreatedAt.Date == targetDate
                && !d.IsDeleted)
            .Select(d => new DprDelaySection(
                d.Task.Name, d.DelayType, d.DelayHours, d.Description))
            .ToListAsync();

        // 3. Labour — approved attendance today
        var labourEntries = await _db.CrewAttendance
            .Where(a => a.ProjectId == projectId
                && a.AttendanceDate.Date == targetDate
                && a.ApprovalStatus == "Approved"
                && !a.IsDeleted)
            .ToListAsync();

        var labour = labourEntries
            .GroupBy(a => a.TradeName ?? "General")
            .Select(g => new DprLabourSection(
                g.Key,
                g.Sum(a => a.PlannedCount ?? 0),
                g.Sum(a => a.ActualCount  ?? 0),
                g.Sum(a => (a.ActualCount ?? 0) - (a.PlannedCount ?? 0))))
            .ToList();

        // 4. High/Critical risks — from project
        var risks = await _db.Risks
            .Where(r => r.ProjectId == projectId
                && (r.RiskLevel == "High" || r.RiskLevel == "Critical")
                && r.Status != "Closed"
                && !r.IsDeleted)
            .Include(r => r.RiskOwner)
            .Select(r => new DprRiskSection(
                r.RiskNumber, r.Title, r.RiskLevel ?? "High",
                r.RiskOwner != null ? r.RiskOwner.FullName : null))
            .Take(10)
            .ToListAsync();

        var totalLabour    = labourEntries.Sum(a => a.ActualCount  ?? 0);
        var totalEquipment = await _db.TaskResourceAllocations
            .Include(a => a.Resource).ThenInclude(r => r.ResourceType)
            .CountAsync(a => a.Task.ProjectId == projectId
                && a.StartDate.Date <= targetDate
                && a.EndDate.Date >= targetDate
                && (a.Resource.ResourceType != null && a.Resource.ResourceType.Category == "Equipment")
                && !a.IsDeleted);

        return new DprCompiledData(workProgress, delays, labour, risks, totalLabour, totalEquipment);
    }

    public string GenerateDprHtml(DPRReport dpr, DprCompiledData data)
    {
        var projectName = dpr.Project?.Name ?? "Project";
        var date = dpr.ReportDate.ToString("dd MMMM yyyy");

        var workRows = data.WorkProgress.Any()
            ? string.Join("", data.WorkProgress.Select(w =>
                $"<tr><td>{w.TaskName}</td><td>{w.ProgressPercent:F0}%</td><td>{w.Status}</td><td>{w.Remarks ?? "—"}</td></tr>"))
            : "<tr><td colspan='4' style='text-align:center;color:#999'>No work progress recorded today</td></tr>";

        var delayRows = data.Delays.Any()
            ? string.Join("", data.Delays.Select(d =>
                $"<tr><td>{d.TaskName}</td><td><span style='color:#ef4444'>{d.DelayType}</span></td><td>{d.Hours}h</td><td>{d.Description ?? "—"}</td></tr>"))
            : "<tr><td colspan='4' style='text-align:center;color:#999'>No delays recorded today</td></tr>";

        var labourRows = data.Labour.Any()
            ? string.Join("", data.Labour.Select(l =>
                $"<tr><td>{l.TradeName}</td><td>{l.Planned}</td><td>{l.Actual}</td><td style='color:{(l.Variance >= 0 ? "#16a34a" : "#dc2626")}'>{(l.Variance >= 0 ? "+" : "")}{l.Variance}</td></tr>"))
            : "<tr><td colspan='4' style='text-align:center;color:#999'>No approved labour entries today</td></tr>";

        var riskRows = data.Risks.Any()
            ? string.Join("", data.Risks.Select(r =>
                $"<tr><td>{r.RiskNumber}</td><td>{r.Title}</td><td style='color:{(r.Severity == "Critical" ? "#ef4444" : "#f97316")}'>{r.Severity}</td><td>{r.Owner ?? "—"}</td></tr>"))
            : "<tr><td colspan='4' style='text-align:center;color:#999'>No high/critical risks open</td></tr>";

        return $@"<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='UTF-8'>
<title>DPR — {date}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', Arial, sans-serif; font-size: 12px; color: #1a1a1a; background: #fff; }}
  .header {{ background: #1a1a1a; color: #FFD700; padding: 20px 30px; display: flex; justify-content: space-between; align-items: center; }}
  .header h1 {{ font-size: 20px; font-weight: 700; }}
  .header .meta {{ text-align: right; font-size: 11px; opacity: 0.8; }}
  .body {{ padding: 24px 30px; }}
  .info-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 24px; }}
  .info-card {{ background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; }}
  .info-card .label {{ font-size: 10px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }}
  .info-card .value {{ font-size: 18px; font-weight: 700; color: #1a1a1a; margin-top: 4px; }}
  .section {{ margin-bottom: 20px; }}
  .section-title {{ font-size: 13px; font-weight: 700; color: #1a1a1a; padding: 8px 12px; background: #FFD700; border-radius: 6px 6px 0 0; }}
  .section-text {{ background: #f9fafb; border: 1px solid #e5e7eb; padding: 10px 12px; border-radius: 0 0 6px 6px; line-height: 1.6; }}
  table {{ width: 100%; border-collapse: collapse; border: 1px solid #e5e7eb; border-radius: 0 0 6px 6px; overflow: hidden; }}
  th {{ background: #f3f4f6; font-weight: 600; font-size: 11px; text-transform: uppercase; letter-spacing: 0.3px; padding: 8px 10px; text-align: left; border-bottom: 1px solid #e5e7eb; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #f0f0f0; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:nth-child(even) {{ background: #fafafa; }}
  .footer {{ margin-top: 30px; padding-top: 15px; border-top: 2px solid #FFD700; display: flex; justify-content: space-between; font-size: 10px; color: #9ca3af; }}
  .status-badge {{ display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 10px; font-weight: 600; }}
  .badge-approved {{ background: #dcfce7; color: #16a34a; }}
  .badge-submitted {{ background: #dbeafe; color: #2563eb; }}
  .badge-draft {{ background: #f3f4f6; color: #6b7280; }}
  @media print {{
    body {{ font-size: 11px; }}
    .header {{ -webkit-print-color-adjust: exact; print-color-adjust: exact; }}
    .section-title {{ -webkit-print-color-adjust: exact; print-color-adjust: exact; }}
  }}
</style>
</head>
<body>
  <div class='header'>
    <div>
      <div style='font-size:11px;opacity:0.7;margin-bottom:4px'>MOUNT MERU GROUP — ENTERPRISE PROJECT MANAGEMENT</div>
      <h1>Daily Progress Report</h1>
      <div style='font-size:13px;margin-top:4px'>{projectName}</div>
    </div>
    <div class='meta'>
      <div style='font-size:16px;font-weight:700'>{date}</div>
      <div style='margin-top:4px'>
        Status: <span class='status-badge badge-{dpr.Status.ToLower()}'>{dpr.Status}</span>
      </div>
      {(dpr.SubmittedBy != null ? $"<div>Submitted by: {dpr.SubmittedBy.FullName}</div>" : "")}
    </div>
  </div>

  <div class='body'>
    <!-- KPI Cards -->
    <div class='info-grid'>
      <div class='info-card'>
        <div class='label'>Total Labour</div>
        <div class='value'>{data.TotalLabour}</div>
      </div>
      <div class='info-card'>
        <div class='label'>Equipment</div>
        <div class='value'>{data.TotalEquipment}</div>
      </div>
      <div class='info-card'>
        <div class='label'>Delays</div>
        <div class='value' style='color:{(data.Delays.Any() ? "#ef4444" : "#16a34a")}'>{data.Delays.Sum(d => d.Hours)}h</div>
      </div>
      <div class='info-card'>
        <div class='label'>Open High Risks</div>
        <div class='value' style='color:{(data.Risks.Any() ? "#f97316" : "#16a34a")}'>{data.Risks.Count}</div>
      </div>
    </div>

    <!-- Site Info -->
    <div class='section'>
      <div class='section-title'>📍 Site Information</div>
      <div class='section-text'>
        <strong>Location of Work:</strong> {dpr.LocationOfWork ?? "Not specified"} &nbsp;&nbsp;
        <strong>Weather:</strong> {dpr.WeatherCondition ?? "Not recorded"} ({dpr.WeatherType ?? "Normal"})
      </div>
    </div>

    <!-- Work Progress -->
    <div class='section'>
      <div class='section-title'>🏗️ Work Progress</div>
      <table>
        <thead><tr><th>Task</th><th>Progress</th><th>Status</th><th>Remarks</th></tr></thead>
        <tbody>{workRows}</tbody>
      </table>
    </div>

    <!-- Labour -->
    <div class='section'>
      <div class='section-title'>👷 Labour Deployment</div>
      <table>
        <thead><tr><th>Trade</th><th>Planned</th><th>Actual</th><th>Variance</th></tr></thead>
        <tbody>{labourRows}</tbody>
      </table>
    </div>

    <!-- Delays -->
    <div class='section'>
      <div class='section-title'>⚠️ Delays</div>
      <table>
        <thead><tr><th>Task</th><th>Delay Type</th><th>Hours Lost</th><th>Description</th></tr></thead>
        <tbody>{delayRows}</tbody>
      </table>
    </div>

    <!-- Risks -->
    <div class='section'>
      <div class='section-title'>🛡️ Active High/Critical Risks</div>
      <table>
        <thead><tr><th>Risk #</th><th>Title</th><th>Severity</th><th>Owner</th></tr></thead>
        <tbody>{riskRows}</tbody>
      </table>
    </div>

    {(string.IsNullOrEmpty(dpr.WorkCompleted) ? "" : $@"
    <div class='section'>
      <div class='section-title'>✅ Work Completed</div>
      <div class='section-text'>{dpr.WorkCompleted}</div>
    </div>")}

    {(string.IsNullOrEmpty(dpr.PlannedForTomorrow) ? "" : $@"
    <div class='section'>
      <div class='section-title'>📋 Planned for Tomorrow</div>
      <div class='section-text'>{dpr.PlannedForTomorrow}</div>
    </div>")}

    {(string.IsNullOrEmpty(dpr.Issues) ? "" : $@"
    <div class='section'>
      <div class='section-title'>🚨 Issues & Concerns</div>
      <div class='section-text' style='color:#dc2626'>{dpr.Issues}</div>
    </div>")}

    {(string.IsNullOrEmpty(dpr.SafetyObservations) ? "" : $@"
    <div class='section'>
      <div class='section-title'>🦺 Safety Observations</div>
      <div class='section-text'>{dpr.SafetyObservations}</div>
    </div>")}

    <div class='footer'>
      <div>Generated by MMG EPM System · {DateTime.Now:dd MMM yyyy HH:mm}</div>
      <div>This is a {(dpr.IsAutoGenerated ? "system-generated" : "manually created")} report</div>
      <div>Mount Meru Group — Confidential</div>
    </div>
  </div>
</body>
</html>";
    }

    // Called by Hangfire CRON at 11AM daily
    public async Task AutoGenerateDailyDprsAsync()
    {
        _logger.LogInformation("Auto-generating DPRs for {Date}", DateTime.Today);

        var activeProjects = await _db.Projects
            .Where(p => p.Status == "Active" && !p.IsDeleted)
            .Select(p => p.Id).ToListAsync();

        var count = 0;
        foreach (var pid in activeProjects)
        {
            // Skip if already exists
            var exists = await _db.DPRReports.AnyAsync(d =>
                d.ProjectId == pid && d.ReportDate.Date == DateTime.Today && !d.IsDeleted);
            if (exists) continue;

            _db.DPRReports.Add(new DPRReport
            {
                ProjectId       = pid,
                ReportDate      = DateTime.Today,
                Status          = "Draft",
                IsAutoGenerated = true,
                WeatherType     = "Normal",
                WeatherCondition = "Clear",
            });
            count++;
        }

        if (count > 0)
        {
            await _db.SaveChangesAsync();
            _logger.LogInformation("Auto-generated {Count} DPR shells", count);
        }
    }
}
